### ISSUE TITLE
IP Address is required

### ISSUE THREAD

**Issue by hraffiest** [jake-walker/wtforms-hcaptcha#2]
Hi!
How do u send user's ip who post form? Thank you
form:
```
class ExtendedLoginForm(FlaskForm):
    """
    Login form
    """
    username = StringField('Имя пользователя', [DataRequired(message='Required field'),
                                        Length(min=4, max=25, message='Ur name must be in from 4 to 25 symbols')])
    password = PasswordField('Пароль',
                             [Length(min=8, max=25, message='Login or password incorrect'),
                              DataRequired(message='Required field')])
    captcha = HcaptchaField(site_key=Config.HCAPTCHA_SITE_KEY, secret_key=Config.HCAPTCHA_SECRET_KEY)
    remember = BooleanField('Запомнить меня', default=True)

```
View:
```
....
@anonymous_user_required
@auth_bp.post('/login')
def login():
    login_form = ExtendedLoginForm()
    register_form = ExtendedRegisterForm()
....

```
Traceback from docker log
```
Traceback (most recent call last):
mmt      |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
mmt      |     self.handle_request(listener, req, client, addr)
mmt      |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
mmt      |     respiter = self.wsgi(environ, resp.start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
mmt      |     return self.wsgi_app(environ, start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
mmt      |     return self.app(environ, start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
mmt      |     response = self.handle_exception(e)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
mmt      |     response = self.full_dispatch_request()
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
mmt      |     rv = self.handle_user_exception(e)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
mmt      |     rv = self.dispatch_request()
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
mmt      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
mmt      |   File "/var/mmt/auth/routes.py", line 68, in login
mmt      |     login_form = ExtendedLoginForm()
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
mmt      |     return type.__call__(cls, *args, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
mmt      |     super().__init__(formdata=formdata, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
mmt      |     self.process(formdata, obj, data=data, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
mmt      |     field.process(formdata)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms_hcaptcha/fields.py", line 54, in process
mmt      |     raise ValueError("IP Address is required.")
mmt      | ValueError: IP Address is required.

```

**Comment by jake-walker** [comment]
Hey, could you please add some of the code that you are using.

**Comment by hraffiest** [comment]
> Hey, could you please add some of the code that you are using.

**Comment by hraffiest** [comment]
> Hey, could you please add some of the code that you are using.

ready

**Comment by hraffiest** [comment]
Now, I am update my endpoint like in ur quick start but error the same.

```
....
@anonymous_user_required
@auth_bp.post('/login')
def login():
    login_form = ExtendedLoginForm(request.form)
    register_form = ExtendedRegisterForm(request.form)
....
```
```
mmt      | [2021-09-30 18:43:33 +0000] [10] [ERROR] Error handling request /auth/login
mmt      | Traceback (most recent call last):
mmt      |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 136, in handle
mmt      |     self.handle_request(listener, req, client, addr)
mmt      |   File "/usr/local/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
mmt      |     respiter = self.wsgi(environ, resp.start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
mmt      |     return self.wsgi_app(environ, start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/werkzeug/middleware/proxy_fix.py", line 187, in __call__
mmt      |     return self.app(environ, start_response)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
mmt      |     response = self.handle_exception(e)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
mmt      |     response = self.full_dispatch_request()
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
mmt      |     rv = self.handle_user_exception(e)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
mmt      |     rv = self.dispatch_request()
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
mmt      |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
mmt      |   File "/var/mmt/auth/routes.py", line 68, in login
mmt      |     login_form = ExtendedLoginForm(request.form)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
mmt      |     return type.__call__(cls, *args, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
mmt      |     super().__init__(formdata=formdata, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
mmt      |     self.process(formdata, obj, data=data, **kwargs)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms/form.py", line 131, in process
mmt      |     field.process(formdata)
mmt      |   File "/usr/local/lib/python3.8/site-packages/wtforms_hcaptcha/fields.py", line 54, in process
mmt      |     raise ValueError("IP Address is required.")
mmt      | ValueError: IP Address is required.

```

**Comment by jake-walker** [comment]
Thanks, apologies for the instructions not being very clear. When you initialise your form, you need to pass in the request IP address.

```python
login_form = ExtendedLoginForm(request.form, captcha={
  "ip_address": request.environ.get("HTTP_X_REAL_IP", request.remote_addr)
})
```

Let me know if that fixes the problem.

**Comment by hraffiest** [comment]
> Thanks, apologies for the instructions not being very clear. When you initialise your form, you need to pass in the request IP address.
> 
> ```python
> login_form = ExtendedLoginForm(request.form, captcha={
>   "ip_address": request.environ.get("HTTP_X_REAL_IP", request.remote_addr)
> })
> ```
> 
> Let me know if that fixes the problem.

It solve the problem, ty for ur time
